services:
  json_spec.helper.json_parser:
    class: Seld\JsonLint\JsonParser

  json_spec.helper.json_helper:
    class: JsonSpec\Helper\JsonHelper
    arguments: [@json_spec.helper.json_parser]

  json_spec.helper.memory_helper:
    class: JsonSpec\Behat\Helper\MemoryHelper

  json_spec.helper.file_helper:
    class: JsonSpec\Helper\FileHelper
    arguments: [%json_spec.json_directory%]

  json_spec.matcher_options_factory:
    class: JsonSpec\MatcherOptionsFactory
    arguments: [%json_spec.excluded_keys%]

  json_spec.matcher:
    class: JsonSpec\JsonSpecMatcher
    arguments: [@json_spec.helper.json_helper, @json_spec.matcher_options_factory]

  json_spec.json_holder:
    class: JsonSpec\Behat\JsonProvider\JsonHolder

  json_spec.json_consumer_aware_initializer:
    class: JsonSpec\Behat\Context\Initializer\JsonHolderAwareInitializer
    arguments: [@json_spec.json_holder]
    tags:
      - {name: context.initializer}

  json_spec.memory_helper_aware_initializer:
    class: JsonSpec\Behat\Context\Initializer\MemoryHelperAwareInitializer
    arguments: [@json_spec.helper.memory_helper]
    tags:
      - {name: context.initializer}

  json_spec.dependency_resolver:
    class: JsonSpec\Behat\Context\ArgumentResolver\DependencyResolver
    arguments:
     - @json_spec.matcher
     - @json_spec.helper.json_helper
     - @json_spec.helper.file_helper
    tags:
      - {name: context.argument_resolver}

  json_spec.context_class_resolver:
    class: JsonSpec\Behat\Context\ContextResolver\JsonSpecContextResolver
    tags:
      - {name: context.class_resolver}
